### ISSUE TITLE
Null Exception PlayerLoginEvent Error on Join

### ISSUE THREAD

**Issue by sensorware** [lucko/ConditionalPerms#6]
When users login I am getting the following error in the logs.  After they login all is all fine, I would like to not have the error in the logs...  Any help would be greatly appreciated.

-------------------------------------------------------
q2u issued server command: /cperms debug
[02:01:09 INFO]: [ConditionalPerms] [DEBUG] Processing permissions for player ToneBone.
[02:01:13 INFO]: ToneBone lost connection: Disconnected
[02:01:13 INFO]: ToneBone left the game
[02:01:17 INFO]: UUID of player ToneBone is f371e10f-60a1-4482-a24b-d2ea0759a912
[02:01:17 INFO]: [ConditionalPerms] [DEBUG] Processing permissions for player ToneBone.
[02:01:17 ERROR]: Could not pass event PlayerLoginEvent to ConditionalPerms v1.3
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at net.minecraft.server.v1_12_R1.PlayerList.attemptLogin(PlayerList.java:525) [gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:133) [gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57) [gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) [gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845) [gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.NullPointerException
at com.sk89q.worldguard.bukkit.RegionContainer.get(RegionContainer.java:236) ~[?:?]
at com.sk89q.worldguard.protection.GlobalRegionManager.get(GlobalRegionManager.java:78) ~[?:?]
at com.sk89q.worldguard.bukkit.RegionQuery.getApplicableRegions(RegionQuery.java:100) ~[?:?]
at me.lucko.conditionalperms.hooks.impl.WorldGuardHook.getRegions(WorldGuardHook.java:45) ~[?:?]
at me.lucko.conditionalperms.hooks.impl.WorldGuardHook.onPlayerLogin(WorldGuardHook.java:61) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45-internal]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45-internal]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45-internal]
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45-internal]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[gbinvl_minecraft_spigot_1_12_1.jar:git-Spigot-edd0396-2a927e8]
... 13 more

**Comment by sensorware** [comment]
resolved, worldguard was not loading correctly from the DB.
